#! /bin/bash

function nl_error {
  echo "waitfor: $*" >&2
  exit 1
}

function print_usage {
cat <<EOF;
waitfor name seconds
  wait for the specified number of seconds for
  the named file or socket to appear.
waitfor name forever
  wait indefinitely for the named file or socket to appear.
waitfor -h
  display this message
EOF
}

[ -z "$1" ] && nl_error Must provide name argument
if [ "$1" = "-h" ]; then
  print_usage
  exit 0
fi
name=$1

[ -z "$2" ] && nl_error Must provide length argument
if [ "$2" = "forever" ]; then
  duration=1
  decrement=0
else
  duration=$2
  decrement=1
fi

while [ $duration -gt 0 ]; do
  [ -e $name ] && exit 0
  sleep 1
  let duration=duration-$decrement
done
exit 1
