#! /bin/bash

function nl_error {
  echo "waitfor: $*" >&2
  exit 1
}

function print_usage {
cat <<EOF;
waitfor [-q] name seconds
  wait for the specified number of seconds for
  the named file or socket to appear.
waitfor [-q] name forever
  wait indefinitely for the named file or socket to appear.
  If not immediately found, will display an informational message.

Options:
  -q Omit informative messages
  
waitfor -h
  display this message
EOF
exit 0
}

opt_quiet=''

while getopts "hq" option; do
  case $option in
    h) print_usage;;
    q) opt_quiet=yes;;
  esac
done
shift $((OPTIND-1))

[ -z "$1" ] && nl_error Must provide name argument
name=$1

[ -z "$2" ] && nl_error Must provide length argument
if [ "$2" = "forever" ]; then
  [ -e $name ] || sleep 1
  [ -e $name -o -n "$opt_quiet" ] || echo "Waiting for $name"
  duration=1
  decrement=0
else
  duration=$2
  decrement=1
fi

while [ $duration -gt 0 ]; do
  [ -e $name ] && exit 0
  sleep 1
  let duration=duration-$decrement
done
exit 1
