#! /bin/bash
opts="$*"
find . -name .git -prune -false -o -type f |
  xargs grep $opts -P "(?:(?:le[-_])das)|dasng|dasctl|linkeng|share/oui"

# This demonstrates that there are essentially no
# references to a bare 'das' or 'DAS', except of
# course in the namespace DAS_IO. It is not appropriate
# to replace that with Monarch, since the library is
# only a piece of the whole.
# find . -name .git -prune -false -o -type f |
#   xargs grep -iP "[^-_a-zA-Z]das\b" |
#   less
