#ifndef NC_TM_CLIENT_H_INCLUDED
#define NC_TM_CLIENT_H_INCLUDED
/** @file nc_tm_client.h
 * Header file for ncurses TM clients
 */

#include <signal.h>
#include "tm_client.h"

namespace DAS_IO {
  
    /**
     * @brief Although very similar to ext_tm_client, nc_tm_client
     * cannot inherit from ext_tm_client. The process_data() method
     * is generated by TMC in extmain.skel in the TM_CLIENT class,
     * so if TM_CLIENT is defined as nc_tm_client and nc_tm_client
     * inherited from ext_tm_client, then the implementation for
     * ext_tm_client::process_data() would be missing.
     */
  class nc_tm_client : public tm_client {
    public:
      inline nc_tm_client(int bufsize, bool fast = true, const char *hostname = 0) :
        tm_client(bufsize, fast, hostname) {}
      unsigned int process_data();
      bool serialized_signal_handler(uint32_t signals_seen);
      void adopted();
  };

}

#endif
